apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: testapp
  name: dconnector
  labels:
    service: testapp
    application: dconnector
    name: dconnector
spec:
  replicas: 1
  selector:
    matchLabels:
      service: testapp
      application: dconnector
      name: dconnector
  template:
    metadata:
      labels:
        service: testapp
        application: dconnector
        name: dconnector
    spec:
      containers:
      - name: dconnector
        image: dconnector:local
        imagePullPolicy: IfNotPresent
        env:
          - name: GROUP_ID
            value: "an-id"
          - name: CONFIG_STORAGE_TOPIC
            value: "testapp"
          - name: OFFSET_STORAGE_TOPIC
            value: "test-app-offset"
---
kind: Service
apiVersion: v1
metadata:
  name: dconnector
  namespace: testapp
spec:
  type: NodePort
  selector:
    application: dconnector
    service: testapp
    name: dconnector
  ports:
  - name: http
    port: 8083
---
